### ISSUE TITLE
Call with core.company.get doesn't get counted as a call in UI

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/developer-hub#40] opened 2015-02-13 20:53 UTC
I did a successful call (response returned data) using core.company.get from here: http://rise-vision.github.io/core-api/, but when I checked here: http://developer.stage.risevision.com/#/apps/list (Sample Code API Explorer), the call was not counted in AVG Calls.

The same call worked fine earlier today.

**Comment by rodrigopavezi** [comment] 2015-02-18 13:40
@AlexKolenoff I found the issue. The queue which tasks are sent to process the requests was down since that day. So I have fixed it and the queue is up and running so everything should work as expected now. I will investigate why the queue gets inactive like it happened. As the user token which comes in the request expires, we cannot get the stats for the request that happened since queue was down. So for avoiding that on the future, we have to make sure the queue does not go down.

@alexey-rise do you know why a queue gets inactive?

 Cheers.

**Comment by rodrigopavezi** [comment] 2015-02-18 16:36
Attempting to this issue with https://github.com/Rise-Vision/core/pull/137

**Comment by alexey-rise** [comment] 2015-02-18 17:11
@rodrigopavezi when was the queue introduced (which branch)? I have been deploying my fixes to `display-transactions2` branch, I wonder if those deployments have been overwriting the queue config with the one that doesn't have your queue in it yet?

**Comment by rodrigopavezi** [comment] 2015-02-18 17:15
@alexey-rise you are right it is not on the display-transactions2 branch https://github.com/Rise-Vision/core/blob/feature/display-transactions2/src/main/webapp/WEB-INF/queue.xml. Are you deploying to rvaserver2 or rvacore-test? cheers

**Comment by alexey-rise** [comment] 2015-02-18 17:20
@rodrigopavezi I have been deploying to rvacore-test. I also deployed a version with 45 idle instances earlier (https://github.com/Rise-Vision/core/pull/127) to rvaserver2.

**Comment by rodrigopavezi** [comment] 2015-02-18 17:44
@alexey-rise I might be wrong but deploying to rvacore-test would not inactive the queue on rvaserver2 right? I saw that you have deployed the https://github.com/Rise-Vision/core/pull/127 but that was 6 days ago. The queue got inactive today after I put it up with an redeployment. That is why I believe that it is going down because of the hight demand. So we could fix it with https://github.com/Rise-Vision/core/pull/137. cheers

**Comment by rodrigopavezi** [comment] 2015-02-19 18:14
@olegrise @alanclayton we have found the cause of the queue issue. Queue was getting disabled because storage server module also had a queue.xml file which did not contain the api monitoring queue. So every time there was a deployment of the storage server it would overwrite the queue definition disabling the api monitoring queue. We have fixed it by removing the queue.xml from storage server project. We can close this issue now. cheers

**Closed** 2015-02-19 18:15 UTC
Labels: bug
